version: '2'

networks:
  nginx-proxy:
    external: true
    
services:
  clientdebian:
   image: clientdebian
   ports:
    - 8070:6080
   networks:
     - nginx-proxy
   environment:
     - VIRTUAL_HOST=clientrecette.formation.squashtest.fr
     - VIRTUAL_PORT=8070
#   environment:
#    - USER=ubuntu
#    - PASSWORD=ubuntu
