version: '2'

volumes:
  database_pg:
    external: true

services:
  
  postgres-ld:
    image: postgres:9.6
    volumes:
      - database_pg:/var/lib/postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  nginx-proxy:
    image: jwilder/nginx-proxy
    environment:
      - COMPOSE_HTTP_TIMEOUT=160
    ports: 
     - "8083:8080"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  logicaldoc:
    image: logicaldoc
    environment:
      - DB_ENGINE=postgres
      - DB_PORT=5432
      - HTTP_PORT=8080
      - DB_HOST=postgres-ld
      - DOCKER_CLIENT_TIMEOUT=120
      - COMPOSE_HTTP_TIMEOUT=160
      - VIRTUAL_HOST=logicaldoc.formation.squashtest.fr
      - VIRTUAL_PORT=8083
    ports:
      - "8080"
    links:
      - postgres-ld
