version: '2'
    
services:
  
   nginx-proxy:
     image: jwilder/nginx-proxy
     environment:
      - COMPOSE_HTTP_TIMEOUT=160
      - VIRTUAL_PORT=83
     ports: 
      - "83:83"
     volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      
