version: '2'

volumes:
  database_my:
   external: true

networks:
  nginx-proxy:
    external: true
  db-network:
  
services:
  
  mysql-ld:
    image: mysql:5.7
    volumes:
     - database_my:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
    networks:
      - db-network

  logicaldoc:
    image: logicaldoc
    environment:
     - DB_ENGINE=mysql
     - DB_HOST=mysql-ld
     - DOCKER_CLIENT_TIMEOUT=120
     - COMPOSE_HTTP_TIMEOUT=120
     - VIRTUAL_HOST=logicaldoc.formation.squashtest.fr
     - VIRTUAL_PORT=8080
    ports:
     - 8080:8080
    links:
     - mysql-ld
    networks:
      - nginx-proxy
      - db-network