version: '2'

volumes:
  database_my:
   external: true
  database_pg:
   external: true

services:
  
  mysql-ld:
    image: mysql:5.7
    volumes:
     - database_my:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports: 
     - "8083:8081"
     - "8093:8080"
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro

  logicaldoc:
    image: logicaldoc
    environment:
     - DB_ENGINE=mysql
     - DOCKER_CLIENT_TIMEOUT=120
     - COMPOSE_HTTP_TIMEOUT=120
     - VIRTUAL_HOST=logicaldoc
     - VIRTUAL_PORT=8081
    ports:
     - "8081"
    links:
     - mysql-ld
