version: '2'

volumes:
  database_my:
   external: true

services:
  
  mysql-ld:
    image: mysql:5.7
    volumes:
     - database_my:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root

  nginx-proxy:
    image: jwilder/nginx-proxy
    environment:
      - COMPOSE_HTTP_TIMEOUT=160
      - VIRTUAL_PORT=83
    ports: 
      - "83:83"
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro

  logicaldoc:
    image: logicaldoc
    environment:
     - DB_ENGINE=mysql
     - DB_HOST=mysql-ld
     - DOCKER_CLIENT_TIMEOUT=120
     - COMPOSE_HTTP_TIMEOUT=120
     - VIRTUAL_HOST=logicaldoc.formation.squashtest.fr
     - VIRTUAL_PORT=8080
    ports:
     - 8080:8080
    links:
     - mysql-ld
